# Generated by Django 4.1.3 on 2022-11-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='skill name')),
                ('exp', models.CharField(max_length=255, verbose_name='skill experience')),
                ('decription', models.TextField()),
            ],
        ),
    ]
