# Generated by Django 4.1.3 on 2022-11-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_skill_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='decription',
            new_name='knowledge',
        ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(blank=True, upload_to='skill_logos/'),
        ),
    ]
