# Generated by Django 4.1.3 on 2022-11-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
