# Generated by Django 4.1.3 on 2022-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, upload_to='project_img/'),
        ),
    ]
